services:
#    server.example:
#        class: ServerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    server.format_service:
        class: ServerBundle\Services\Format

    server.user_service:
        class: ServerBundle\Services\UserService

    server.geo_service:
        class: ServerBundle\Services\GeolocalisationService

    server.gcm_service:
        class: ServerBundle\Services\GCMService
        arguments: ['%gcm_api_key%']

