services:
#    server.example:
#        class: ServerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    server.format_service:
        class: ServerBundle\Services\Format
